### ISSUE TITLE
Add support for multi-post messages

### ISSUE THREAD

**Issue by oliviasculley** [codeforgreenville/c4g-events#11]
Slack's API caps the number of available blocks to 50, which is a max of around 20 events per week. To get around this problem, we should support breaking up posts into multiple slack messages if there are more than 50 blocks

Ideally, we'll need several changes to fix this:
- Instead of storing posts with a primary key of week, we'll need to store them per week + count
  - We'll need to support update existing databases to the new database schema, as well
- We need to support splitting up posts into multiple parts, text and block formats
- We need to support checking with the saved version of the post in the database, in order to determine whether to update them or not

Acceptance Criteria:
- The app can break up posts into multiple slack messages
- There are tests to ensure that posts are broken up into multiple slack messages with less than 50 blocks each
- There are tests that validate that posts are only updated when they change, which may include one part of a series of slack messages

**Comment by allella** [comment]
What is a "block"? 

Would we be able to get more around the issue if the text for each event were trimmed down so we avoid hitting the limit?

**Comment by oliviasculley** [comment]
When composing a message with more dynamic formatting, each "element", such a header, dividing line, or group of text is a separate block.
There's a [slack bot kit builder](https://app.slack.com/block-kit-builder) which will let you play around with blocks, but here's a picture of how we're using separate blocks in an events post, which you can see starting from [here](https://github.com/hackgvl/slack-events-bot/blob/1dc2f52f4a62fa9a2ad2092e25274705d6955737/src/event.py#LL46C1-L46C1) in the code:

![2023-06-19_14-06-1687200479](https://github.com/hackgvl/slack-events-bot/assets/88074048/210396bb-007c-4717-8009-57bd859d341e)

**Comment by allella** [comment]
I think it looks good, but it is probably more verbose than needed.  A lot of the descriptions on events are the same month-to-month, so I'd put that on the top of the list if we are going to pare things down.  Also, the div lines are nice, but shouldn't been needed if we make the event's title a smaller header h# element (assuming that's possible).

Also, Synergy Mill agreed to remove the recurring activities from their meetup at a recent event, so you'll have 4 or so fewer events every week when they stop posting tasks / activities as events.
