### ISSUE TITLE
Event Messages Can Exceed Slack's Maxmimum Message Length

### ISSUE THREAD

**Issue by ThorntonMatthewD** [codeforgreenville/c4g-events#44]
```
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/chat.update, status: 200)
The server responded with: {'ok': False, 'error': 'msg_too_long'}
```

The above error can be thrown from within [post_or_update_messages](https://github.com/hackgvl/slack-events-bot/blob/f8b800e7ad31ba891c6d9c47726d8212f4e2cfe7/src/bot.py#L24) -- specifically wherever `APP.client.chat_postMessage` is called -- whenever `text`'s length exceeds Slack's 4k character limit (see [here](https://api.slack.com/docs/rate-limits#rtm-posting-messages)).

**Comment by oliviasculley** [comment]
FYI, this is most likely a duplicate of #11

**Comment by ThorntonMatthewD** [comment]
It definitely is. I'll close this one out.
