### ISSUE TITLE
Paginated Posts Showing Incorrect Total: "2 of 1"

### ISSUE THREAD

**Issue by ThorntonMatthewD** [codeforgreenville/c4g-events#52]
![Screenshot_20231209-111014](https://github.com/hackgvl/slack-events-bot/assets/44626690/bb1d4008-6603-4e1b-8dc7-a9f8cc5ca20b)

A new event was added for the week of Dec 10th that caused a spillover from there being one message for that week to two. That is intended behavior.

What isn't intended behavior is the header of the second post reading "HackGreenville Events for the week of December 10 - 2 of 1".

It should instead be "HackGreenville Events for the week of December 10 - 2 of 2" in this instance.

**Comment by ThorntonMatthewD** [comment]
The remediation has been validated.

* ### [Post 1](https://hackgreenville.slack.com/archives/C042530GC/p1701838859929929)
![Screenshot_2023-12-09_21-29-09](https://github.com/hackgvl/slack-events-bot/assets/44626690/65b71a9e-64d0-45ba-b3b7-82031b0c63d3)

* ### [Post 2](https://hackgreenville.slack.com/archives/C042530GC/p1702115002260529)
![Screenshot_2023-12-09_21-29-15](https://github.com/hackgvl/slack-events-bot/assets/44626690/5b4d4e4f-32e0-43ff-83db-8ed6d1b72803)

**Comment by allella** [comment]
Nice work.
